package export

import (
	"fmt"
	"io"
	"sort"
	"strings"
	"time"

	"github.com/jung-kurt/gofpdf"
)

type PDFReport struct {
	pdf         *gofpdf.Fpdf
	title       string
	module      string
	generatedBy string
	theme       moduleTheme
	generatedAt time.Time
}

func NewPDFReport(title, module, generatedBy string) *PDFReport {
	theme := themeForModule(module)
	report := &PDFReport{
		pdf:         gofpdf.New("L", "mm", "A4", ""),
		title:       strings.TrimSpace(title),
		module:      strings.TrimSpace(module),
		generatedBy: strings.TrimSpace(generatedBy),
		theme:       theme,
		generatedAt: time.Now(),
	}

	report.pdf.SetTitle(report.title, false)
	report.pdf.SetAuthor("KANTOR", false)
	report.pdf.SetMargins(14, 18, 14)
	report.pdf.SetAutoPageBreak(true, 18)
	report.pdf.AliasNbPages("{nb}")
	report.pdf.SetHeaderFuncMode(report.drawHeader, true)
	report.pdf.SetFooterFunc(report.drawFooter)
	report.pdf.AddPage()

	return report
}

func (r *PDFReport) AddSection(title string) {
	r.pdf.Ln(2)
	r.pdf.SetFont("Arial", "B", 13)
	r.pdf.SetTextColor(r.theme.HeaderRGB[0], r.theme.HeaderRGB[1], r.theme.HeaderRGB[2])
	r.pdf.CellFormat(0, 8, strings.TrimSpace(title), "", 1, "L", false, 0, "")
	r.pdf.SetTextColor(23, 43, 77)
}

func (r *PDFReport) AddParagraph(text string) {
	trimmed := strings.TrimSpace(text)
	if trimmed == "" {
		return
	}

	r.pdf.SetFont("Arial", "", 10)
	r.pdf.SetTextColor(80, 95, 121)
	r.pdf.MultiCell(0, 5.5, trimmed, "", "L", false)
	r.pdf.SetTextColor(23, 43, 77)
	r.pdf.Ln(1)
}

func (r *PDFReport) AddSummary(data map[string]string) {
	if len(data) == 0 {
		return
	}

	keys := make([]string, 0, len(data))
	for key := range data {
		keys = append(keys, key)
	}
	sort.Strings(keys)

	r.pdf.Ln(1)
	boxWidth := 110.0
	if len(keys) > 4 {
		boxWidth = 130
	}

	startX := r.pdf.GetX()
	startY := r.pdf.GetY()
	lineHeight := 6.5
	padding := 4.0
	boxHeight := padding*2 + float64(len(keys))*lineHeight

	r.pdf.SetFillColor(244, 245, 247)
	r.pdf.SetDrawColor(223, 225, 230)
	r.pdf.RoundedRect(startX, startY, boxWidth, boxHeight, 3, "1234", "FD")

	r.pdf.SetXY(startX+padding, startY+padding)
	for _, key := range keys {
		r.pdf.SetFont("Arial", "B", 10)
		r.pdf.SetTextColor(66, 82, 110)
		r.pdf.CellFormat(40, lineHeight, key, "", 0, "L", false, 0, "")
		r.pdf.SetFont("Arial", "", 10)
		r.pdf.SetTextColor(23, 43, 77)
		r.pdf.CellFormat(boxWidth-40-padding*2, lineHeight, data[key], "", 1, "L", false, 0, "")
		r.pdf.SetX(startX + padding)
	}

	r.pdf.SetXY(startX, startY+boxHeight+3)
	r.pdf.SetTextColor(23, 43, 77)
}

func (r *PDFReport) AddTable(headers []string, rows [][]string) {
	if len(headers) == 0 {
		return
	}

	pageWidth, _ := r.pdf.GetPageSize()
	left, _, right, _ := r.pdf.GetMargins()
	usableWidth := pageWidth - left - right
	colWidth := usableWidth / float64(len(headers))

	r.pdf.SetFont("Arial", "B", 10)
	r.pdf.SetFillColor(r.theme.HeaderRGB[0], r.theme.HeaderRGB[1], r.theme.HeaderRGB[2])
	r.pdf.SetTextColor(255, 255, 255)
	r.pdf.SetDrawColor(223, 225, 230)

	for _, header := range headers {
		r.pdf.CellFormat(colWidth, 8, truncatePDFCell(header, 32), "1", 0, "C", true, 0, "")
	}
	r.pdf.Ln(-1)

	r.pdf.SetFont("Arial", "", 9)
	r.pdf.SetTextColor(23, 43, 77)
	for rowIndex, row := range rows {
		if rowIndex%2 == 0 {
			r.pdf.SetFillColor(255, 255, 255)
		} else {
			r.pdf.SetFillColor(244, 245, 247)
		}

		for cellIndex := range headers {
			value := ""
			if cellIndex < len(row) {
				value = row[cellIndex]
			}
			r.pdf.CellFormat(colWidth, 7, truncatePDFCell(value, 38), "1", 0, "L", true, 0, "")
		}
		r.pdf.Ln(-1)
	}

	r.pdf.Ln(2)
}

func (r *PDFReport) AddPageBreak() {
	r.pdf.AddPage()
}

func (r *PDFReport) Save(writer io.Writer) error {
	return r.pdf.Output(writer)
}

func (r *PDFReport) drawHeader() {
	r.pdf.SetFont("Arial", "B", 18)
	r.pdf.SetTextColor(23, 43, 77)
	r.pdf.CellFormat(38, 8, "KANTOR", "", 0, "L", false, 0, "")

	r.pdf.SetFont("Arial", "B", 14)
	r.pdf.SetTextColor(r.theme.HeaderRGB[0], r.theme.HeaderRGB[1], r.theme.HeaderRGB[2])
	r.pdf.CellFormat(0, 8, strings.ToUpper(r.theme.Label), "", 1, "L", false, 0, "")

	r.pdf.SetFont("Arial", "B", 16)
	r.pdf.SetTextColor(23, 43, 77)
	r.pdf.CellFormat(0, 9, r.title, "", 1, "L", false, 0, "")

	r.pdf.SetFont("Arial", "", 10)
	r.pdf.SetTextColor(80, 95, 121)
	r.pdf.CellFormat(0, 6, fmt.Sprintf("Generated on %s", r.generatedAt.Format("02 January 2006 15:04 WIB")), "", 1, "L", false, 0, "")
	r.pdf.Ln(3)
}

func (r *PDFReport) drawFooter() {
	r.pdf.SetY(-12)
	r.pdf.SetFont("Arial", "", 9)
	r.pdf.SetTextColor(80, 95, 121)
	byline := "Generated by KANTOR"
	if r.generatedBy != "" {
		byline = fmt.Sprintf("Generated by %s", r.generatedBy)
	}
	r.pdf.CellFormat(0, 6, fmt.Sprintf("%s — %s — Page %d of {nb}", byline, r.generatedAt.Format("02 January 2006 15:04 WIB"), r.pdf.PageNo()), "", 0, "C", false, 0, "")
}

func truncatePDFCell(value string, maxRunes int) string {
	trimmed := strings.TrimSpace(value)
	if trimmed == "" {
		return "-"
	}

	runes := []rune(trimmed)
	if len(runes) <= maxRunes {
		return trimmed
	}

	return string(runes[:maxRunes-1]) + "…"
}

