/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedForbiddenRouteImport } from './routes/_authenticated/forbidden'
import { Route as AuthenticatedOperationalIndexRouteImport } from './routes/_authenticated/operational/index'
import { Route as AuthenticatedMarketingIndexRouteImport } from './routes/_authenticated/marketing/index'
import { Route as AuthenticatedHrisIndexRouteImport } from './routes/_authenticated/hris/index'
import { Route as AuthenticatedOperationalWaBroadcastRouteImport } from './routes/_authenticated/operational/wa-broadcast'
import { Route as AuthenticatedOperationalTrackerRouteImport } from './routes/_authenticated/operational/tracker'
import { Route as AuthenticatedOperationalOverviewRouteImport } from './routes/_authenticated/operational/overview'
import { Route as AuthenticatedMarketingOverviewRouteImport } from './routes/_authenticated/marketing/overview'
import { Route as AuthenticatedMarketingLeadsRouteImport } from './routes/_authenticated/marketing/leads'
import { Route as AuthenticatedMarketingDashboardRouteImport } from './routes/_authenticated/marketing/dashboard'
import { Route as AuthenticatedMarketingCampaignsRouteImport } from './routes/_authenticated/marketing/campaigns'
import { Route as AuthenticatedMarketingAdsMetricsRouteImport } from './routes/_authenticated/marketing/ads-metrics'
import { Route as AuthenticatedHrisSubscriptionsRouteImport } from './routes/_authenticated/hris/subscriptions'
import { Route as AuthenticatedHrisOverviewRouteImport } from './routes/_authenticated/hris/overview'
import { Route as AuthenticatedHrisFinanceRouteImport } from './routes/_authenticated/hris/finance'
import { Route as AuthenticatedHrisDepartmentsRouteImport } from './routes/_authenticated/hris/departments'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedAdminRolesRouteImport } from './routes/_authenticated/admin/roles'
import { Route as AuthenticatedAdminRegistrationRouteImport } from './routes/_authenticated/admin/registration'
import { Route as AuthenticatedAdminAuditLogsRouteImport } from './routes/_authenticated/admin/audit-logs'
import { Route as AuthenticatedOperationalVpsIndexRouteImport } from './routes/_authenticated/operational/vps/index'
import { Route as AuthenticatedOperationalProjectsIndexRouteImport } from './routes/_authenticated/operational/projects/index'
import { Route as AuthenticatedOperationalDomainsIndexRouteImport } from './routes/_authenticated/operational/domains/index'
import { Route as AuthenticatedHrisReimbursementsIndexRouteImport } from './routes/_authenticated/hris/reimbursements/index'
import { Route as AuthenticatedHrisEmployeesIndexRouteImport } from './routes/_authenticated/hris/employees/index'
import { Route as AuthenticatedOperationalVpsVpsIDRouteImport } from './routes/_authenticated/operational/vps/$vpsID'
import { Route as AuthenticatedOperationalProjectsProjectIdRouteImport } from './routes/_authenticated/operational/projects/$projectId'
import { Route as AuthenticatedOperationalDomainsDomainIDRouteImport } from './routes/_authenticated/operational/domains/$domainID'
import { Route as AuthenticatedHrisReimbursementsReimbursementIdRouteImport } from './routes/_authenticated/hris/reimbursements/$reimbursementId'
import { Route as AuthenticatedHrisEmployeesEmployeeIdRouteImport } from './routes/_authenticated/hris/employees/$employeeId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedForbiddenRoute = AuthenticatedForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOperationalIndexRoute =
  AuthenticatedOperationalIndexRouteImport.update({
    id: '/operational/',
    path: '/operational/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMarketingIndexRoute =
  AuthenticatedMarketingIndexRouteImport.update({
    id: '/marketing/',
    path: '/marketing/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHrisIndexRoute = AuthenticatedHrisIndexRouteImport.update({
  id: '/hris/',
  path: '/hris/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOperationalWaBroadcastRoute =
  AuthenticatedOperationalWaBroadcastRouteImport.update({
    id: '/operational/wa-broadcast',
    path: '/operational/wa-broadcast',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOperationalTrackerRoute =
  AuthenticatedOperationalTrackerRouteImport.update({
    id: '/operational/tracker',
    path: '/operational/tracker',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOperationalOverviewRoute =
  AuthenticatedOperationalOverviewRouteImport.update({
    id: '/operational/overview',
    path: '/operational/overview',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMarketingOverviewRoute =
  AuthenticatedMarketingOverviewRouteImport.update({
    id: '/marketing/overview',
    path: '/marketing/overview',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMarketingLeadsRoute =
  AuthenticatedMarketingLeadsRouteImport.update({
    id: '/marketing/leads',
    path: '/marketing/leads',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMarketingDashboardRoute =
  AuthenticatedMarketingDashboardRouteImport.update({
    id: '/marketing/dashboard',
    path: '/marketing/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMarketingCampaignsRoute =
  AuthenticatedMarketingCampaignsRouteImport.update({
    id: '/marketing/campaigns',
    path: '/marketing/campaigns',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMarketingAdsMetricsRoute =
  AuthenticatedMarketingAdsMetricsRouteImport.update({
    id: '/marketing/ads-metrics',
    path: '/marketing/ads-metrics',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHrisSubscriptionsRoute =
  AuthenticatedHrisSubscriptionsRouteImport.update({
    id: '/hris/subscriptions',
    path: '/hris/subscriptions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHrisOverviewRoute =
  AuthenticatedHrisOverviewRouteImport.update({
    id: '/hris/overview',
    path: '/hris/overview',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHrisFinanceRoute =
  AuthenticatedHrisFinanceRouteImport.update({
    id: '/hris/finance',
    path: '/hris/finance',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHrisDepartmentsRoute =
  AuthenticatedHrisDepartmentsRouteImport.update({
    id: '/hris/departments',
    path: '/hris/departments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/admin/settings',
    path: '/admin/settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminRolesRoute = AuthenticatedAdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRegistrationRoute =
  AuthenticatedAdminRegistrationRouteImport.update({
    id: '/admin/registration',
    path: '/admin/registration',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminAuditLogsRoute =
  AuthenticatedAdminAuditLogsRouteImport.update({
    id: '/admin/audit-logs',
    path: '/admin/audit-logs',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOperationalVpsIndexRoute =
  AuthenticatedOperationalVpsIndexRouteImport.update({
    id: '/operational/vps/',
    path: '/operational/vps/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOperationalProjectsIndexRoute =
  AuthenticatedOperationalProjectsIndexRouteImport.update({
    id: '/operational/projects/',
    path: '/operational/projects/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOperationalDomainsIndexRoute =
  AuthenticatedOperationalDomainsIndexRouteImport.update({
    id: '/operational/domains/',
    path: '/operational/domains/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHrisReimbursementsIndexRoute =
  AuthenticatedHrisReimbursementsIndexRouteImport.update({
    id: '/hris/reimbursements/',
    path: '/hris/reimbursements/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHrisEmployeesIndexRoute =
  AuthenticatedHrisEmployeesIndexRouteImport.update({
    id: '/hris/employees/',
    path: '/hris/employees/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOperationalVpsVpsIDRoute =
  AuthenticatedOperationalVpsVpsIDRouteImport.update({
    id: '/operational/vps/$vpsID',
    path: '/operational/vps/$vpsID',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOperationalProjectsProjectIdRoute =
  AuthenticatedOperationalProjectsProjectIdRouteImport.update({
    id: '/operational/projects/$projectId',
    path: '/operational/projects/$projectId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOperationalDomainsDomainIDRoute =
  AuthenticatedOperationalDomainsDomainIDRouteImport.update({
    id: '/operational/domains/$domainID',
    path: '/operational/domains/$domainID',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHrisReimbursementsReimbursementIdRoute =
  AuthenticatedHrisReimbursementsReimbursementIdRouteImport.update({
    id: '/hris/reimbursements/$reimbursementId',
    path: '/hris/reimbursements/$reimbursementId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHrisEmployeesEmployeeIdRoute =
  AuthenticatedHrisEmployeesEmployeeIdRouteImport.update({
    id: '/hris/employees/$employeeId',
    path: '/hris/employees/$employeeId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/forbidden': typeof AuthenticatedForbiddenRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/admin/audit-logs': typeof AuthenticatedAdminAuditLogsRoute
  '/admin/registration': typeof AuthenticatedAdminRegistrationRoute
  '/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/hris/departments': typeof AuthenticatedHrisDepartmentsRoute
  '/hris/finance': typeof AuthenticatedHrisFinanceRoute
  '/hris/overview': typeof AuthenticatedHrisOverviewRoute
  '/hris/subscriptions': typeof AuthenticatedHrisSubscriptionsRoute
  '/marketing/ads-metrics': typeof AuthenticatedMarketingAdsMetricsRoute
  '/marketing/campaigns': typeof AuthenticatedMarketingCampaignsRoute
  '/marketing/dashboard': typeof AuthenticatedMarketingDashboardRoute
  '/marketing/leads': typeof AuthenticatedMarketingLeadsRoute
  '/marketing/overview': typeof AuthenticatedMarketingOverviewRoute
  '/operational/overview': typeof AuthenticatedOperationalOverviewRoute
  '/operational/tracker': typeof AuthenticatedOperationalTrackerRoute
  '/operational/wa-broadcast': typeof AuthenticatedOperationalWaBroadcastRoute
  '/hris/': typeof AuthenticatedHrisIndexRoute
  '/marketing/': typeof AuthenticatedMarketingIndexRoute
  '/operational/': typeof AuthenticatedOperationalIndexRoute
  '/hris/employees/$employeeId': typeof AuthenticatedHrisEmployeesEmployeeIdRoute
  '/hris/reimbursements/$reimbursementId': typeof AuthenticatedHrisReimbursementsReimbursementIdRoute
  '/operational/domains/$domainID': typeof AuthenticatedOperationalDomainsDomainIDRoute
  '/operational/projects/$projectId': typeof AuthenticatedOperationalProjectsProjectIdRoute
  '/operational/vps/$vpsID': typeof AuthenticatedOperationalVpsVpsIDRoute
  '/hris/employees/': typeof AuthenticatedHrisEmployeesIndexRoute
  '/hris/reimbursements/': typeof AuthenticatedHrisReimbursementsIndexRoute
  '/operational/domains/': typeof AuthenticatedOperationalDomainsIndexRoute
  '/operational/projects/': typeof AuthenticatedOperationalProjectsIndexRoute
  '/operational/vps/': typeof AuthenticatedOperationalVpsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/forbidden': typeof AuthenticatedForbiddenRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/admin/audit-logs': typeof AuthenticatedAdminAuditLogsRoute
  '/admin/registration': typeof AuthenticatedAdminRegistrationRoute
  '/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/hris/departments': typeof AuthenticatedHrisDepartmentsRoute
  '/hris/finance': typeof AuthenticatedHrisFinanceRoute
  '/hris/overview': typeof AuthenticatedHrisOverviewRoute
  '/hris/subscriptions': typeof AuthenticatedHrisSubscriptionsRoute
  '/marketing/ads-metrics': typeof AuthenticatedMarketingAdsMetricsRoute
  '/marketing/campaigns': typeof AuthenticatedMarketingCampaignsRoute
  '/marketing/dashboard': typeof AuthenticatedMarketingDashboardRoute
  '/marketing/leads': typeof AuthenticatedMarketingLeadsRoute
  '/marketing/overview': typeof AuthenticatedMarketingOverviewRoute
  '/operational/overview': typeof AuthenticatedOperationalOverviewRoute
  '/operational/tracker': typeof AuthenticatedOperationalTrackerRoute
  '/operational/wa-broadcast': typeof AuthenticatedOperationalWaBroadcastRoute
  '/hris': typeof AuthenticatedHrisIndexRoute
  '/marketing': typeof AuthenticatedMarketingIndexRoute
  '/operational': typeof AuthenticatedOperationalIndexRoute
  '/hris/employees/$employeeId': typeof AuthenticatedHrisEmployeesEmployeeIdRoute
  '/hris/reimbursements/$reimbursementId': typeof AuthenticatedHrisReimbursementsReimbursementIdRoute
  '/operational/domains/$domainID': typeof AuthenticatedOperationalDomainsDomainIDRoute
  '/operational/projects/$projectId': typeof AuthenticatedOperationalProjectsProjectIdRoute
  '/operational/vps/$vpsID': typeof AuthenticatedOperationalVpsVpsIDRoute
  '/hris/employees': typeof AuthenticatedHrisEmployeesIndexRoute
  '/hris/reimbursements': typeof AuthenticatedHrisReimbursementsIndexRoute
  '/operational/domains': typeof AuthenticatedOperationalDomainsIndexRoute
  '/operational/projects': typeof AuthenticatedOperationalProjectsIndexRoute
  '/operational/vps': typeof AuthenticatedOperationalVpsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/forbidden': typeof AuthenticatedForbiddenRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/admin/audit-logs': typeof AuthenticatedAdminAuditLogsRoute
  '/_authenticated/admin/registration': typeof AuthenticatedAdminRegistrationRoute
  '/_authenticated/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/hris/departments': typeof AuthenticatedHrisDepartmentsRoute
  '/_authenticated/hris/finance': typeof AuthenticatedHrisFinanceRoute
  '/_authenticated/hris/overview': typeof AuthenticatedHrisOverviewRoute
  '/_authenticated/hris/subscriptions': typeof AuthenticatedHrisSubscriptionsRoute
  '/_authenticated/marketing/ads-metrics': typeof AuthenticatedMarketingAdsMetricsRoute
  '/_authenticated/marketing/campaigns': typeof AuthenticatedMarketingCampaignsRoute
  '/_authenticated/marketing/dashboard': typeof AuthenticatedMarketingDashboardRoute
  '/_authenticated/marketing/leads': typeof AuthenticatedMarketingLeadsRoute
  '/_authenticated/marketing/overview': typeof AuthenticatedMarketingOverviewRoute
  '/_authenticated/operational/overview': typeof AuthenticatedOperationalOverviewRoute
  '/_authenticated/operational/tracker': typeof AuthenticatedOperationalTrackerRoute
  '/_authenticated/operational/wa-broadcast': typeof AuthenticatedOperationalWaBroadcastRoute
  '/_authenticated/hris/': typeof AuthenticatedHrisIndexRoute
  '/_authenticated/marketing/': typeof AuthenticatedMarketingIndexRoute
  '/_authenticated/operational/': typeof AuthenticatedOperationalIndexRoute
  '/_authenticated/hris/employees/$employeeId': typeof AuthenticatedHrisEmployeesEmployeeIdRoute
  '/_authenticated/hris/reimbursements/$reimbursementId': typeof AuthenticatedHrisReimbursementsReimbursementIdRoute
  '/_authenticated/operational/domains/$domainID': typeof AuthenticatedOperationalDomainsDomainIDRoute
  '/_authenticated/operational/projects/$projectId': typeof AuthenticatedOperationalProjectsProjectIdRoute
  '/_authenticated/operational/vps/$vpsID': typeof AuthenticatedOperationalVpsVpsIDRoute
  '/_authenticated/hris/employees/': typeof AuthenticatedHrisEmployeesIndexRoute
  '/_authenticated/hris/reimbursements/': typeof AuthenticatedHrisReimbursementsIndexRoute
  '/_authenticated/operational/domains/': typeof AuthenticatedOperationalDomainsIndexRoute
  '/_authenticated/operational/projects/': typeof AuthenticatedOperationalProjectsIndexRoute
  '/_authenticated/operational/vps/': typeof AuthenticatedOperationalVpsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/forbidden'
    | '/profile'
    | '/admin/audit-logs'
    | '/admin/registration'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/users'
    | '/hris/departments'
    | '/hris/finance'
    | '/hris/overview'
    | '/hris/subscriptions'
    | '/marketing/ads-metrics'
    | '/marketing/campaigns'
    | '/marketing/dashboard'
    | '/marketing/leads'
    | '/marketing/overview'
    | '/operational/overview'
    | '/operational/tracker'
    | '/operational/wa-broadcast'
    | '/hris/'
    | '/marketing/'
    | '/operational/'
    | '/hris/employees/$employeeId'
    | '/hris/reimbursements/$reimbursementId'
    | '/operational/domains/$domainID'
    | '/operational/projects/$projectId'
    | '/operational/vps/$vpsID'
    | '/hris/employees/'
    | '/hris/reimbursements/'
    | '/operational/domains/'
    | '/operational/projects/'
    | '/operational/vps/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/forbidden'
    | '/profile'
    | '/admin/audit-logs'
    | '/admin/registration'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/users'
    | '/hris/departments'
    | '/hris/finance'
    | '/hris/overview'
    | '/hris/subscriptions'
    | '/marketing/ads-metrics'
    | '/marketing/campaigns'
    | '/marketing/dashboard'
    | '/marketing/leads'
    | '/marketing/overview'
    | '/operational/overview'
    | '/operational/tracker'
    | '/operational/wa-broadcast'
    | '/hris'
    | '/marketing'
    | '/operational'
    | '/hris/employees/$employeeId'
    | '/hris/reimbursements/$reimbursementId'
    | '/operational/domains/$domainID'
    | '/operational/projects/$projectId'
    | '/operational/vps/$vpsID'
    | '/hris/employees'
    | '/hris/reimbursements'
    | '/operational/domains'
    | '/operational/projects'
    | '/operational/vps'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/_authenticated/forbidden'
    | '/_authenticated/profile'
    | '/_authenticated/admin/audit-logs'
    | '/_authenticated/admin/registration'
    | '/_authenticated/admin/roles'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/users'
    | '/_authenticated/hris/departments'
    | '/_authenticated/hris/finance'
    | '/_authenticated/hris/overview'
    | '/_authenticated/hris/subscriptions'
    | '/_authenticated/marketing/ads-metrics'
    | '/_authenticated/marketing/campaigns'
    | '/_authenticated/marketing/dashboard'
    | '/_authenticated/marketing/leads'
    | '/_authenticated/marketing/overview'
    | '/_authenticated/operational/overview'
    | '/_authenticated/operational/tracker'
    | '/_authenticated/operational/wa-broadcast'
    | '/_authenticated/hris/'
    | '/_authenticated/marketing/'
    | '/_authenticated/operational/'
    | '/_authenticated/hris/employees/$employeeId'
    | '/_authenticated/hris/reimbursements/$reimbursementId'
    | '/_authenticated/operational/domains/$domainID'
    | '/_authenticated/operational/projects/$projectId'
    | '/_authenticated/operational/vps/$vpsID'
    | '/_authenticated/hris/employees/'
    | '/_authenticated/hris/reimbursements/'
    | '/_authenticated/operational/domains/'
    | '/_authenticated/operational/projects/'
    | '/_authenticated/operational/vps/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/forbidden': {
      id: '/_authenticated/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof AuthenticatedForbiddenRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/operational/': {
      id: '/_authenticated/operational/'
      path: '/operational'
      fullPath: '/operational/'
      preLoaderRoute: typeof AuthenticatedOperationalIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/marketing/': {
      id: '/_authenticated/marketing/'
      path: '/marketing'
      fullPath: '/marketing/'
      preLoaderRoute: typeof AuthenticatedMarketingIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hris/': {
      id: '/_authenticated/hris/'
      path: '/hris'
      fullPath: '/hris/'
      preLoaderRoute: typeof AuthenticatedHrisIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/operational/wa-broadcast': {
      id: '/_authenticated/operational/wa-broadcast'
      path: '/operational/wa-broadcast'
      fullPath: '/operational/wa-broadcast'
      preLoaderRoute: typeof AuthenticatedOperationalWaBroadcastRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/operational/tracker': {
      id: '/_authenticated/operational/tracker'
      path: '/operational/tracker'
      fullPath: '/operational/tracker'
      preLoaderRoute: typeof AuthenticatedOperationalTrackerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/operational/overview': {
      id: '/_authenticated/operational/overview'
      path: '/operational/overview'
      fullPath: '/operational/overview'
      preLoaderRoute: typeof AuthenticatedOperationalOverviewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/marketing/overview': {
      id: '/_authenticated/marketing/overview'
      path: '/marketing/overview'
      fullPath: '/marketing/overview'
      preLoaderRoute: typeof AuthenticatedMarketingOverviewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/marketing/leads': {
      id: '/_authenticated/marketing/leads'
      path: '/marketing/leads'
      fullPath: '/marketing/leads'
      preLoaderRoute: typeof AuthenticatedMarketingLeadsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/marketing/dashboard': {
      id: '/_authenticated/marketing/dashboard'
      path: '/marketing/dashboard'
      fullPath: '/marketing/dashboard'
      preLoaderRoute: typeof AuthenticatedMarketingDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/marketing/campaigns': {
      id: '/_authenticated/marketing/campaigns'
      path: '/marketing/campaigns'
      fullPath: '/marketing/campaigns'
      preLoaderRoute: typeof AuthenticatedMarketingCampaignsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/marketing/ads-metrics': {
      id: '/_authenticated/marketing/ads-metrics'
      path: '/marketing/ads-metrics'
      fullPath: '/marketing/ads-metrics'
      preLoaderRoute: typeof AuthenticatedMarketingAdsMetricsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hris/subscriptions': {
      id: '/_authenticated/hris/subscriptions'
      path: '/hris/subscriptions'
      fullPath: '/hris/subscriptions'
      preLoaderRoute: typeof AuthenticatedHrisSubscriptionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hris/overview': {
      id: '/_authenticated/hris/overview'
      path: '/hris/overview'
      fullPath: '/hris/overview'
      preLoaderRoute: typeof AuthenticatedHrisOverviewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hris/finance': {
      id: '/_authenticated/hris/finance'
      path: '/hris/finance'
      fullPath: '/hris/finance'
      preLoaderRoute: typeof AuthenticatedHrisFinanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hris/departments': {
      id: '/_authenticated/hris/departments'
      path: '/hris/departments'
      fullPath: '/hris/departments'
      preLoaderRoute: typeof AuthenticatedHrisDepartmentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/roles': {
      id: '/_authenticated/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AuthenticatedAdminRolesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/registration': {
      id: '/_authenticated/admin/registration'
      path: '/admin/registration'
      fullPath: '/admin/registration'
      preLoaderRoute: typeof AuthenticatedAdminRegistrationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/audit-logs': {
      id: '/_authenticated/admin/audit-logs'
      path: '/admin/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AuthenticatedAdminAuditLogsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/operational/vps/': {
      id: '/_authenticated/operational/vps/'
      path: '/operational/vps'
      fullPath: '/operational/vps/'
      preLoaderRoute: typeof AuthenticatedOperationalVpsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/operational/projects/': {
      id: '/_authenticated/operational/projects/'
      path: '/operational/projects'
      fullPath: '/operational/projects/'
      preLoaderRoute: typeof AuthenticatedOperationalProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/operational/domains/': {
      id: '/_authenticated/operational/domains/'
      path: '/operational/domains'
      fullPath: '/operational/domains/'
      preLoaderRoute: typeof AuthenticatedOperationalDomainsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hris/reimbursements/': {
      id: '/_authenticated/hris/reimbursements/'
      path: '/hris/reimbursements'
      fullPath: '/hris/reimbursements/'
      preLoaderRoute: typeof AuthenticatedHrisReimbursementsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hris/employees/': {
      id: '/_authenticated/hris/employees/'
      path: '/hris/employees'
      fullPath: '/hris/employees/'
      preLoaderRoute: typeof AuthenticatedHrisEmployeesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/operational/vps/$vpsID': {
      id: '/_authenticated/operational/vps/$vpsID'
      path: '/operational/vps/$vpsID'
      fullPath: '/operational/vps/$vpsID'
      preLoaderRoute: typeof AuthenticatedOperationalVpsVpsIDRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/operational/projects/$projectId': {
      id: '/_authenticated/operational/projects/$projectId'
      path: '/operational/projects/$projectId'
      fullPath: '/operational/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedOperationalProjectsProjectIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/operational/domains/$domainID': {
      id: '/_authenticated/operational/domains/$domainID'
      path: '/operational/domains/$domainID'
      fullPath: '/operational/domains/$domainID'
      preLoaderRoute: typeof AuthenticatedOperationalDomainsDomainIDRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hris/reimbursements/$reimbursementId': {
      id: '/_authenticated/hris/reimbursements/$reimbursementId'
      path: '/hris/reimbursements/$reimbursementId'
      fullPath: '/hris/reimbursements/$reimbursementId'
      preLoaderRoute: typeof AuthenticatedHrisReimbursementsReimbursementIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hris/employees/$employeeId': {
      id: '/_authenticated/hris/employees/$employeeId'
      path: '/hris/employees/$employeeId'
      fullPath: '/hris/employees/$employeeId'
      preLoaderRoute: typeof AuthenticatedHrisEmployeesEmployeeIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedForbiddenRoute: typeof AuthenticatedForbiddenRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedAdminAuditLogsRoute: typeof AuthenticatedAdminAuditLogsRoute
  AuthenticatedAdminRegistrationRoute: typeof AuthenticatedAdminRegistrationRoute
  AuthenticatedAdminRolesRoute: typeof AuthenticatedAdminRolesRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedHrisDepartmentsRoute: typeof AuthenticatedHrisDepartmentsRoute
  AuthenticatedHrisFinanceRoute: typeof AuthenticatedHrisFinanceRoute
  AuthenticatedHrisOverviewRoute: typeof AuthenticatedHrisOverviewRoute
  AuthenticatedHrisSubscriptionsRoute: typeof AuthenticatedHrisSubscriptionsRoute
  AuthenticatedMarketingAdsMetricsRoute: typeof AuthenticatedMarketingAdsMetricsRoute
  AuthenticatedMarketingCampaignsRoute: typeof AuthenticatedMarketingCampaignsRoute
  AuthenticatedMarketingDashboardRoute: typeof AuthenticatedMarketingDashboardRoute
  AuthenticatedMarketingLeadsRoute: typeof AuthenticatedMarketingLeadsRoute
  AuthenticatedMarketingOverviewRoute: typeof AuthenticatedMarketingOverviewRoute
  AuthenticatedOperationalOverviewRoute: typeof AuthenticatedOperationalOverviewRoute
  AuthenticatedOperationalTrackerRoute: typeof AuthenticatedOperationalTrackerRoute
  AuthenticatedOperationalWaBroadcastRoute: typeof AuthenticatedOperationalWaBroadcastRoute
  AuthenticatedHrisIndexRoute: typeof AuthenticatedHrisIndexRoute
  AuthenticatedMarketingIndexRoute: typeof AuthenticatedMarketingIndexRoute
  AuthenticatedOperationalIndexRoute: typeof AuthenticatedOperationalIndexRoute
  AuthenticatedHrisEmployeesEmployeeIdRoute: typeof AuthenticatedHrisEmployeesEmployeeIdRoute
  AuthenticatedHrisReimbursementsReimbursementIdRoute: typeof AuthenticatedHrisReimbursementsReimbursementIdRoute
  AuthenticatedOperationalDomainsDomainIDRoute: typeof AuthenticatedOperationalDomainsDomainIDRoute
  AuthenticatedOperationalProjectsProjectIdRoute: typeof AuthenticatedOperationalProjectsProjectIdRoute
  AuthenticatedOperationalVpsVpsIDRoute: typeof AuthenticatedOperationalVpsVpsIDRoute
  AuthenticatedHrisEmployeesIndexRoute: typeof AuthenticatedHrisEmployeesIndexRoute
  AuthenticatedHrisReimbursementsIndexRoute: typeof AuthenticatedHrisReimbursementsIndexRoute
  AuthenticatedOperationalDomainsIndexRoute: typeof AuthenticatedOperationalDomainsIndexRoute
  AuthenticatedOperationalProjectsIndexRoute: typeof AuthenticatedOperationalProjectsIndexRoute
  AuthenticatedOperationalVpsIndexRoute: typeof AuthenticatedOperationalVpsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedForbiddenRoute: AuthenticatedForbiddenRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedAdminAuditLogsRoute: AuthenticatedAdminAuditLogsRoute,
  AuthenticatedAdminRegistrationRoute: AuthenticatedAdminRegistrationRoute,
  AuthenticatedAdminRolesRoute: AuthenticatedAdminRolesRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedHrisDepartmentsRoute: AuthenticatedHrisDepartmentsRoute,
  AuthenticatedHrisFinanceRoute: AuthenticatedHrisFinanceRoute,
  AuthenticatedHrisOverviewRoute: AuthenticatedHrisOverviewRoute,
  AuthenticatedHrisSubscriptionsRoute: AuthenticatedHrisSubscriptionsRoute,
  AuthenticatedMarketingAdsMetricsRoute: AuthenticatedMarketingAdsMetricsRoute,
  AuthenticatedMarketingCampaignsRoute: AuthenticatedMarketingCampaignsRoute,
  AuthenticatedMarketingDashboardRoute: AuthenticatedMarketingDashboardRoute,
  AuthenticatedMarketingLeadsRoute: AuthenticatedMarketingLeadsRoute,
  AuthenticatedMarketingOverviewRoute: AuthenticatedMarketingOverviewRoute,
  AuthenticatedOperationalOverviewRoute: AuthenticatedOperationalOverviewRoute,
  AuthenticatedOperationalTrackerRoute: AuthenticatedOperationalTrackerRoute,
  AuthenticatedOperationalWaBroadcastRoute:
    AuthenticatedOperationalWaBroadcastRoute,
  AuthenticatedHrisIndexRoute: AuthenticatedHrisIndexRoute,
  AuthenticatedMarketingIndexRoute: AuthenticatedMarketingIndexRoute,
  AuthenticatedOperationalIndexRoute: AuthenticatedOperationalIndexRoute,
  AuthenticatedHrisEmployeesEmployeeIdRoute:
    AuthenticatedHrisEmployeesEmployeeIdRoute,
  AuthenticatedHrisReimbursementsReimbursementIdRoute:
    AuthenticatedHrisReimbursementsReimbursementIdRoute,
  AuthenticatedOperationalDomainsDomainIDRoute:
    AuthenticatedOperationalDomainsDomainIDRoute,
  AuthenticatedOperationalProjectsProjectIdRoute:
    AuthenticatedOperationalProjectsProjectIdRoute,
  AuthenticatedOperationalVpsVpsIDRoute: AuthenticatedOperationalVpsVpsIDRoute,
  AuthenticatedHrisEmployeesIndexRoute: AuthenticatedHrisEmployeesIndexRoute,
  AuthenticatedHrisReimbursementsIndexRoute:
    AuthenticatedHrisReimbursementsIndexRoute,
  AuthenticatedOperationalDomainsIndexRoute:
    AuthenticatedOperationalDomainsIndexRoute,
  AuthenticatedOperationalProjectsIndexRoute:
    AuthenticatedOperationalProjectsIndexRoute,
  AuthenticatedOperationalVpsIndexRoute: AuthenticatedOperationalVpsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
