/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedForbiddenRouteImport } from './routes/_authenticated/forbidden'
import { Route as AuthenticatedOperationalIndexRouteImport } from './routes/_authenticated/operational/index'
import { Route as AuthenticatedMarketingIndexRouteImport } from './routes/_authenticated/marketing/index'
import { Route as AuthenticatedHrisIndexRouteImport } from './routes/_authenticated/hris/index'
import { Route as AuthenticatedOperationalAutomationRouteImport } from './routes/_authenticated/operational/automation'
import { Route as AuthenticatedOperationalProjectsIndexRouteImport } from './routes/_authenticated/operational/projects/index'
import { Route as AuthenticatedOperationalProjectsProjectIdRouteImport } from './routes/_authenticated/operational/projects/$projectId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedForbiddenRoute = AuthenticatedForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOperationalIndexRoute =
  AuthenticatedOperationalIndexRouteImport.update({
    id: '/operational/',
    path: '/operational/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMarketingIndexRoute =
  AuthenticatedMarketingIndexRouteImport.update({
    id: '/marketing/',
    path: '/marketing/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHrisIndexRoute = AuthenticatedHrisIndexRouteImport.update({
  id: '/hris/',
  path: '/hris/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOperationalAutomationRoute =
  AuthenticatedOperationalAutomationRouteImport.update({
    id: '/operational/automation',
    path: '/operational/automation',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOperationalProjectsIndexRoute =
  AuthenticatedOperationalProjectsIndexRouteImport.update({
    id: '/operational/projects/',
    path: '/operational/projects/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOperationalProjectsProjectIdRoute =
  AuthenticatedOperationalProjectsProjectIdRouteImport.update({
    id: '/operational/projects/$projectId',
    path: '/operational/projects/$projectId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/forbidden': typeof AuthenticatedForbiddenRoute
  '/operational/automation': typeof AuthenticatedOperationalAutomationRoute
  '/hris/': typeof AuthenticatedHrisIndexRoute
  '/marketing/': typeof AuthenticatedMarketingIndexRoute
  '/operational/': typeof AuthenticatedOperationalIndexRoute
  '/operational/projects/$projectId': typeof AuthenticatedOperationalProjectsProjectIdRoute
  '/operational/projects/': typeof AuthenticatedOperationalProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/forbidden': typeof AuthenticatedForbiddenRoute
  '/operational/automation': typeof AuthenticatedOperationalAutomationRoute
  '/hris': typeof AuthenticatedHrisIndexRoute
  '/marketing': typeof AuthenticatedMarketingIndexRoute
  '/operational': typeof AuthenticatedOperationalIndexRoute
  '/operational/projects/$projectId': typeof AuthenticatedOperationalProjectsProjectIdRoute
  '/operational/projects': typeof AuthenticatedOperationalProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/forbidden': typeof AuthenticatedForbiddenRoute
  '/_authenticated/operational/automation': typeof AuthenticatedOperationalAutomationRoute
  '/_authenticated/hris/': typeof AuthenticatedHrisIndexRoute
  '/_authenticated/marketing/': typeof AuthenticatedMarketingIndexRoute
  '/_authenticated/operational/': typeof AuthenticatedOperationalIndexRoute
  '/_authenticated/operational/projects/$projectId': typeof AuthenticatedOperationalProjectsProjectIdRoute
  '/_authenticated/operational/projects/': typeof AuthenticatedOperationalProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/forbidden'
    | '/operational/automation'
    | '/hris/'
    | '/marketing/'
    | '/operational/'
    | '/operational/projects/$projectId'
    | '/operational/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/forbidden'
    | '/operational/automation'
    | '/hris'
    | '/marketing'
    | '/operational'
    | '/operational/projects/$projectId'
    | '/operational/projects'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/_authenticated/forbidden'
    | '/_authenticated/operational/automation'
    | '/_authenticated/hris/'
    | '/_authenticated/marketing/'
    | '/_authenticated/operational/'
    | '/_authenticated/operational/projects/$projectId'
    | '/_authenticated/operational/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/forbidden': {
      id: '/_authenticated/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof AuthenticatedForbiddenRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/operational/': {
      id: '/_authenticated/operational/'
      path: '/operational'
      fullPath: '/operational/'
      preLoaderRoute: typeof AuthenticatedOperationalIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/marketing/': {
      id: '/_authenticated/marketing/'
      path: '/marketing'
      fullPath: '/marketing/'
      preLoaderRoute: typeof AuthenticatedMarketingIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hris/': {
      id: '/_authenticated/hris/'
      path: '/hris'
      fullPath: '/hris/'
      preLoaderRoute: typeof AuthenticatedHrisIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/operational/automation': {
      id: '/_authenticated/operational/automation'
      path: '/operational/automation'
      fullPath: '/operational/automation'
      preLoaderRoute: typeof AuthenticatedOperationalAutomationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/operational/projects/': {
      id: '/_authenticated/operational/projects/'
      path: '/operational/projects'
      fullPath: '/operational/projects/'
      preLoaderRoute: typeof AuthenticatedOperationalProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/operational/projects/$projectId': {
      id: '/_authenticated/operational/projects/$projectId'
      path: '/operational/projects/$projectId'
      fullPath: '/operational/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedOperationalProjectsProjectIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedForbiddenRoute: typeof AuthenticatedForbiddenRoute
  AuthenticatedOperationalAutomationRoute: typeof AuthenticatedOperationalAutomationRoute
  AuthenticatedHrisIndexRoute: typeof AuthenticatedHrisIndexRoute
  AuthenticatedMarketingIndexRoute: typeof AuthenticatedMarketingIndexRoute
  AuthenticatedOperationalIndexRoute: typeof AuthenticatedOperationalIndexRoute
  AuthenticatedOperationalProjectsProjectIdRoute: typeof AuthenticatedOperationalProjectsProjectIdRoute
  AuthenticatedOperationalProjectsIndexRoute: typeof AuthenticatedOperationalProjectsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedForbiddenRoute: AuthenticatedForbiddenRoute,
  AuthenticatedOperationalAutomationRoute:
    AuthenticatedOperationalAutomationRoute,
  AuthenticatedHrisIndexRoute: AuthenticatedHrisIndexRoute,
  AuthenticatedMarketingIndexRoute: AuthenticatedMarketingIndexRoute,
  AuthenticatedOperationalIndexRoute: AuthenticatedOperationalIndexRoute,
  AuthenticatedOperationalProjectsProjectIdRoute:
    AuthenticatedOperationalProjectsProjectIdRoute,
  AuthenticatedOperationalProjectsIndexRoute:
    AuthenticatedOperationalProjectsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
